/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
#include "callbacks.h"
#include "dupa.h"

GtkListStore *listStore;
GtkTreeIter iter;

int
main (int argc, char *argv[])
{
  GtkWidget *mainWindow;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  /*add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps"); */

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  mainWindow = create_mainWindow ();
  gtk_widget_show (mainWindow);

  GtkWidget *timeEntry = lookup_widget (GTK_WIDGET (mainWindow), "timeEntry");
  GtkWidget *history = lookup_widget (GTK_WIDGET (mainWindow), "historyView");
  GtkStyle *style = gtk_widget_get_style (timeEntry);
  pango_font_description_set_weight (style->font_desc, PANGO_WEIGHT_BOLD);
  gtk_widget_modify_font (timeEntry, style->font_desc);
  gtk_entry_set_text (GTK_ENTRY (timeEntry), "00:00:00.0");

  listStore = gtk_list_store_new (N_COLUMNS, G_TYPE_UINT, G_TYPE_STRING);
  gtk_tree_view_set_model (GTK_TREE_VIEW (history),
			   GTK_TREE_MODEL (listStore));

  GtkCellRenderer *renderer;

  renderer = gtk_cell_renderer_text_new ();
  gtk_tree_view_insert_column_with_attributes (GTK_TREE_VIEW (history),
					       -1,
					       "Pos",
					       renderer,
					       "text", COLUMN_POS, NULL);

  renderer = gtk_cell_renderer_text_new ();
  gtk_tree_view_insert_column_with_attributes (GTK_TREE_VIEW (history),
					       -1,
					       "Time",
					       renderer,
					       "text", COLUMN_TIME, NULL);

  gtk_main ();
  return 0;
}
